name: Not Just Studies
favicon: null
layout_spectrum: 0.38206964870914817
typography_spectrum: 0.8488488220609725
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8063388948794454
  lightness: 0.461673527257517
  saturation: 0.13052748912014067
  rhythmicContrast: 0.4690078143030405
purpose: []
