name: Not Just Studies
favicon: null
layout_spectrum: 0.06233
typography_spectrum: 0.84372
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#060709'
    - '#94a2ab'
    - '#d3147b'
    - '#f47b20'
  brandStrength: 0.875
  lightness: 0.461673527257517
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
