name: Not Just Studies
favicon: null
layout_spectrum: 0.729
typography_spectrum: 0.84372
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#002060'
    - '#ffffff'
    - '#00b050'
    - '#4f6591'
    - '#5fcd91'
  brandStrength: 0.875
  lightness: 0.461673527257517
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
